name = "alarms"
main = "build/worker/shim.mjs"
compatibility_date = "2026-03-08"

[build]
command = "cargo install -q worker-build && worker-build --release"

[limits]
cpu_ms = 45000

[[kv_namespaces]]
binding = "CACHE"
id = "b30ee945018a4393b61c52f756fac0f0"
