name = "alarms"
main = "entry.py"
compatibility_date = "2026-03-08"
compatibility_flags = ["python_workers"]

[limits]
cpu_ms = 45000

[[kv_namespaces]]
binding = "CACHE"
id = "b30ee945018a4393b61c52f756fac0f0"
