#!/usr/bin/env python3
"""Generate worker-rs/src/city_translations.rs from city_translations.py."""
import sys, os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from city_translations import CITY_TRANSLATIONS

out_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "worker-rs", "src", "city_translations.rs"
)

lines = [
    "// AUTO-GENERATED by tools/gen_city_translations.py — do not edit by hand.",
    "// Re-generate with: python3 tools/gen_city_translations.py",
    "",
    "/// Hebrew→English city name lookup. 1627 entries.",
    "pub fn translate(hebrew: &str) -> Option<&'static str> {",
    "    CITIES.binary_search_by_key(&hebrew, |&(k, _)| k)",
    "        .ok()",
    "        .map(|i| CITIES[i].1)",
    "}",
    "",
    "static CITIES: &[(&str, &str)] = &[",
]

# Sort by key so binary_search works
for k, v in sorted(CITY_TRANSLATIONS.items()):
    k_esc = k.replace('\\', '\\\\').replace('"', '\\"')
    v_esc = v.replace('\\', '\\\\').replace('"', '\\"')
    lines.append(f'    ("{k_esc}", "{v_esc}"),')

lines += ["];", ""]

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Wrote {len(CITY_TRANSLATIONS)} entries to {out_path}")
